spring:
  application:
    name: member-list-app

  # H2 Database Configuration
  datasource:
    url: jdbc:h2:mem:memberdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 

  # H2 Console Configuration (for development)
  h2:
    console:
      enabled: true
      path: /h2-console

  # JPA Configuration
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# Logging Configuration
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
